local loadedLevel = false
local enabledLevel = false

function init(self)
	msg.post(".", "acquire_input_focus")
	go.set_position(vmath.vector3(960, 1080/2, 0.75))
	go.set("#sprite", "tint.w", 0.0)
end


function on_message(self, message_id, message, sender)
	if message_id == hash("startGame") and not loadedLevel then
		msg.post("loader:/loaderProxy", "loadLevel")
		msg.post("loader:/loaderProxy", "unloadMain")
		loadedLevel = true
	end
end
